<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>Ris.ShaderToolkit</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.0.0" />
  </ItemGroup>

  <!-- This enables native assets to be automatically copied when the project is referenced -->
  <!-- Works during build, publish, and when packed as NuGet -->
  <ItemGroup>
    <None Include="runtimes\**\*"
          Pack="true"
          PackagePath="runtimes\"
          CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>